lib/nou_rau_web/router.ex
defmodule NouRauWeb.Router do
  use NouRauWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {NouRauWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", NouRauWeb do
    pipe_through :browser

    live "/", PageLive, :index
    live "/documents", DocumentLive.Index, :index
    live "/documents/new", DocumentLive.Index, :new
    live "/documents/:id/edit", DocumentLive.Index, :edit
    live "/documents/:id", DocumentLive.Show, :show
    live "/documents/:id/show/edit", DocumentLive.Show, :edit
    get "/documents/:id/download", DocumentController, :download

    live "/categories", CategoryLive.Index, :index
    live "/categories/new", CategoryLive.Index, :new
    live "/categories/:id/edit", CategoryLive.Index, :edit
    live "/categories/:id", CategoryLive.Show, :show
    live "/categories/:id/show/edit", CategoryLive.Show, :edit
  end

  # Other scopes may use custom stacks.
  # scope "/api", NouRauWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: NouRauWeb.Telemetry
    end
  end
end

lib/nou_rau_web/live/category_live/form_component.ex
defmodule NouRauWeb.CategoryLive.FormComponent do
  use NouRauWeb, :live_component

  alias NouRau.Collections

  @impl true
  def update(%{category: category} = assigns, socket) do
    changeset = Collections.change_category(category)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"category" => category_params}, socket) do
    changeset =
      socket.assigns.category
      |> Collections.change_category(category_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"category" => category_params}, socket) do
    save_category(socket, socket.assigns.action, category_params)
  end

  defp save_category(socket, :edit, category_params) do
    case Collections.update_category(socket.assigns.category, category_params) do
      {:ok, _category} ->
        {:noreply,
         socket
         |> put_flash(:info, "Category updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_category(socket, :new, category_params) do
    case Collections.create_category(category_params) do
      {:ok, _category} ->
        {:noreply,
         socket
         |> put_flash(:info, "Category created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/nou_rau_web/live/category_live/index.ex
defmodule NouRauWeb.CategoryLive.Index do
  use NouRauWeb, :live_view

  alias NouRau.Collections
  alias NouRau.Collections.Category

  @impl true
  def mount(_params, _session, socket) do
    socket = assign(socket, :categories, [])
    {:ok, socket}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Category")
    |> assign(:categories, Collections.list_categories_for_another())
    |> assign(:category, Collections.get_category!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Category")
    |> assign(:category, %Category{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Categories")
    |> assign(:categories, Collections.list_categories_with_subcategories_count())
    |> assign(:category, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    category = Collections.get_category!(id)
    {:ok, _} = Collections.delete_category(category)

    {:noreply, assign(socket, :categories, list_categories())}
  end

  defp list_categories do
    Collections.list_categories()
  end
end

lib/nou_rau_web/live/category_live/show.ex
defmodule NouRauWeb.CategoryLive.Show do
  use NouRauWeb, :live_view

  alias NouRau.Collections

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:category, Collections.get_category!(id))}
  end

  defp page_title(:show), do: "Show Category"
  defp page_title(:edit), do: "Edit Category"
end

lib/nou_rau_web/live/document_live/form_component.ex
defmodule NouRauWeb.DocumentLive.FormComponent do
  use NouRauWeb, :live_component

  alias NouRau.Collections
  alias NouRau.Collections.{Attachment, Document, Upload}

  @impl true
  def update(%{document: document} = assigns, socket) do
    changeset = Collections.change_document(document)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)
     |> allow_upload(:attachment, accept: Upload.allowed_extensions())}
  end

  @impl true
  def handle_event("validate", %{"document" => document_params}, socket) do
    changeset =
      socket.assigns.document
      |> Collections.change_document(document_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"document" => document_params}, socket) do
    save_document(socket, socket.assigns.action, document_params)
  end

  defp save_document(socket, :edit, document_params) do
    document = put_document_file(socket, socket.assigns.document)

    case Collections.update_document(document, document_params, &consume_attachments(socket, &1)) do
      {:ok, _document} ->
        {:noreply,
         socket
         |> put_flash(:info, "Document updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_document(socket, :new, document_params) do
    document = put_document_file(socket, %Document{})

    case Collections.create_document_from(document, document_params, &consume_attachments(socket, &1)) do
      {:ok, _document} ->
        {:noreply,
         socket
         |> put_flash(:info, "Document created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end

  defp put_document_file(socket, %Document{} = document) do
    {[entry|_], []} = uploaded_entries(socket, :attachment)
    file_path = Routes.static_path(socket, "/uploads/" <> Upload.filename(entry))
    attachment = %Attachment{file_path: file_path, original_filename: "hardcoded.txt"}

    %Document{document | attachment: attachment}
  end

  defp consume_attachments(socket, %Document{} = document) do
    consume_uploaded_entries(socket, :attachment, &Upload.new_entry/2)
    {:ok, document}
  end
end

lib/nou_rau_web/live/document_live/index.ex
defmodule NouRauWeb.DocumentLive.Index do
  use NouRauWeb, :live_view

  alias NouRau.Collections
  alias NouRau.Collections.Document

  @impl true
  def mount(_params, _session, socket) do
    socket = assign(
      socket,
      documents: Collections.list_documents(),
      categories: Collections.list_categories()
    )
    {:ok, socket}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Document")
    |> assign(:document, Collections.get_document!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Document")
    |> assign(:document, %Document{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Documents")
    |> assign(:document, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    document = Collections.get_document!(id)
    {:ok, _} = Collections.delete_document(document)

    {:noreply, assign(socket, :documents, list_documents())}
  end

  defp list_documents do
    Collections.list_documents()
  end
end

lib/nou_rau_web/live/document_live/show.ex
defmodule NouRauWeb.DocumentLive.Show do
  use NouRauWeb, :live_view

  alias NouRau.Collections

  @impl true
  def mount(_params, _session, socket) do
    socket = assign(socket, categories: Collections.list_categories())
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:document, Collections.get_document!(id))}
  end

  defp page_title(:show), do: "Show Document"
  defp page_title(:edit), do: "Edit Document"
end

lib/nou_rau_web/live/live_helpers.ex
defmodule NouRauWeb.LiveHelpers do
  import Phoenix.LiveView.Helpers

  @doc """
  Renders a component inside the `NouRauWeb.ModalComponent` component.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <%= live_modal @socket, NouRauWeb.DocumentLive.FormComponent,
        id: @document.id || :new,
        action: @live_action,
        document: @document,
        return_to: Routes.document_index_path(@socket, :index) %>
  """
  def live_modal(socket, component, opts) do
    path = Keyword.fetch!(opts, :return_to)
    modal_opts = [id: :modal, return_to: path, component: component, opts: opts]
    live_component(socket, NouRauWeb.ModalComponent, modal_opts)
  end
end

lib/nou_rau_web/live/modal_component.ex
defmodule NouRauWeb.ModalComponent do
  use NouRauWeb, :live_component

  @impl true
  def render(assigns) do
    ~L"""
    <div id="<%= @id %>" class="phx-modal"
      phx-capture-click="close"
      phx-window-keydown="close"
      phx-key="escape"
      phx-target="#<%= @id %>"
      phx-page-loading>

      <div class="phx-modal-content">
        <%= live_patch raw("&times;"), to: @return_to, class: "phx-modal-close" %>
        <%= live_component @socket, @component, @opts %>
      </div>
    </div>
    """
  end

  @impl true
  def handle_event("close", _, socket) do
    {:noreply, push_patch(socket, to: socket.assigns.return_to)}
  end
end

lib/nou_rau_web/live/page_live.ex
defmodule NouRauWeb.PageLive do
  use NouRauWeb, :live_view
  alias NouRau.Collections

  @impl true
  def mount(_params, _session, socket) do
    assigns = assign(socket,
      query: "",
      results: %{},
      root_categories: Collections.root_categories(),
      # TODO: to adjust when downloads counter available
      most_downloaded_documents: most_downloaded_documents()
    )

    {:ok, assigns}
  end

  @impl true
  def handle_event("suggest", %{"q" => query}, socket) do
    {:noreply, assign(socket, results: search(query), query: query)}
  end

  @impl true
  def handle_event("search", %{"q" => query}, socket) do
    case search(query) do
      %{^query => vsn} ->
        {:noreply, redirect(socket, external: "https://hexdocs.pm/#{query}/#{vsn}")}

      _ ->
        {:noreply,
         socket
         |> put_flash(:error, "No dependencies found matching \"#{query}\"")
         |> assign(results: %{}, query: query)}
    end
  end

  defp search(query) do
    if not NouRauWeb.Endpoint.config(:code_reloader) do
      raise "action disabled when not in development"
    end

    for {app, desc, vsn} <- Application.started_applications(),
        app = to_string(app),
        String.starts_with?(app, query) and not List.starts_with?(desc, ~c"ERTS"),
        into: %{},
        do: {app, vsn}
  end

  defp most_downloaded_documents do
    Collections.list_documents() |> Enum.take(10)
  end
end

lib/nou_rau_web/live/document_live/form_component.html.leex
<h2><%= @title %></h2>

<%= f = form_for @changeset, "#",
  id: "document-form",
  phx_target: @myself,
  phx_change: "validate",
  phx_submit: "save" %>

  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>

  <%= label f, :description %>
  <%= text_input f, :description %>
  <%= error_tag f, :description %>

  <%= label f, :category_id %>
  <%= select f, :category_id, Enum.map(@categories, &{&1.name, &1.id}) %>
  <%= error_tag f, :category_id %>

  <div>
    <%= if @document.attachment do %>
      <a href="#"><%= @document.attachment.original_filename %></a>

    <% else %>
      <%= label f, :file %>
      <%= live_file_input @uploads.attachment %>

      <%= for attachment <- @uploads.attachment.entries do %>
        <span class="column">
            <progress max="100" value="<%= attachment.progress %>" />
        </span>
      <% end %>

    <%= end %>

    <%= for {_ref, msg} <- @uploads.attachment.errors do %>
      <p class="alert alert-danger">
          <%= Phoenix.Naming.humanize(msg) %>
      </p>
    <% end %>
  </div>

  <div>
    <%= submit "Save", phx_disable_with: "Saving..." %>
  </div>

</form>

lib/nou_rau_web/live/document_live/index.html.leex
<h1>Listing Documents</h1>

<%= if @live_action in [:new, :edit] do %>
  <%= live_modal @socket, NouRauWeb.DocumentLive.FormComponent,
    id: @document.id || :new,
    title: @page_title,
    action: @live_action,
    document: @document,
    categories: @categories,
    return_to: Routes.document_index_path(@socket, :index) %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Category</th>

      <th></th>
    </tr>
  </thead>
  <tbody id="documents">
    <%= for document <- @documents do %>
      <tr id="document-<%= document.id %>">
        <td><%= document.name %></td>
        <td><%= document.description %></td>
        <td><%= live_redirect document.category.name, to: Routes.category_show_path(@socket, :show, document.category) %></td>

        <td>
          <span><%= live_redirect "Show", to: Routes.document_show_path(@socket, :show, document) %></span>
          <span><%= live_patch "Edit", to: Routes.document_index_path(@socket, :edit, document) %></span>
          <span><%= link "Delete", to: "#", phx_click: "delete", phx_value_id: document.id, data: [confirm: "Are you sure?"] %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<span><%= live_patch "New Document", to: Routes.document_index_path(@socket, :new) %></span>

lib/nou_rau_web/live/document_live/show.html.leex
<h1>Show Document</h1>

<%= if @live_action in [:edit] do %>
  <%= live_modal @socket, NouRauWeb.DocumentLive.FormComponent,
    id: @document.id,
    title: @page_title,
    action: @live_action,
    document: @document,
    categories: @categories,
    return_to: Routes.document_show_path(@socket, :show, @document) %>
<% end %>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @document.name %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @document.description || "(no description)" %>
  </li>

  <li>
      <strong>Category:</strong>
      <%= @document.category.name %>
  </li>

  <%= if @document.attachment do %>
    <li>
        <strong>File:</strong>
        <%= @document.attachment.original_filename %>
    </li>
  <% else %>
    <li>
        <strong>File:</strong>
        No attachment yet
    </li>
  <% end %>

  <li>
    <strong>Inserted at:</strong>
    <%= @document.inserted_at %>
  </li>

  <li>
    <strong>Updated at:</strong>
    <%= @document.updated_at %>
  </li>

</ul>

<span><%= live_patch "Edit", to: Routes.document_show_path(@socket, :edit, @document), class: "button" %></span>
<span><%= live_redirect "Back", to: Routes.document_index_path(@socket, :index) %></span>